const elInput1 = document.querySelector("#inp1");
const elInput2 = document.querySelector("#inp2");
const elInput3 = document.querySelector("#inp3");
const elResult = document.querySelector(".result");
document.querySelector("#btn").onclick = function () {
  const res = document.createElement("div");
  res.style.border = "solid rgb(172, 170, 170, 0.3)";
  res.style.borderRadius = "5px";
  res.style.backgroundColor = "rgb(244, 242, 242)";
  const elInputs1 = document.createElement("p");
  const elInputs2 = document.createElement("p");
  const elInputs3 = document.createElement("p");
  elInputs1.style.paddingTop = "5px";
  elInputs1.style.fontSize = "38px";
  elInputs1.style.fontWeight = "800px";
  elInputs1.style.marginLeft = "10px";
  elInputs2.style.paddingTop = "10px";
  elInputs2.style.fontSize = "24px";
  elInputs2.style.fontWeight = "100px";
  elInputs2.style.marginLeft = "10px";
  elInputs3.style.paddingTop = "10px";
  elInputs3.style.paddingBottom = "10px";
  elInputs3.style.marginLeft = "10px";
  elInputs3.style.fontSize = "24px";
  elInputs3.style.color = "dodgerblue";
  elInputs1.textContent = elInput1.value;
  elInputs2.textContent = elInput2.value;
  elInputs3.textContent = elInput3.value;
  res.append(elInputs1);
  res.append(elInputs2);
  res.append(elInputs3);
  elResult.appendChild(res);
};
document.querySelector("#clear").onclick = function () {
  elInput1.value = "";
  elInput2.value = "";
  elInput3.value = "";
  elResult.innerHTML = "";
};
